"""Stable machine-readable planning reason and review codes."""

from enum import StrEnum


class ReasonCode(StrEnum):
    """Initial reason vocabulary shared by future planning results."""

    MISSING_PREREQUISITE = "MISSING_PREREQUISITE"
    ALREADY_COMPLETED = "ALREADY_COMPLETED"
    CURRENTLY_REGISTERED = "CURRENTLY_REGISTERED"
    WRONG_REGULATION = "WRONG_REGULATION"
    WRONG_PROGRAM = "WRONG_PROGRAM"
    UNVERIFIED_RULE = "UNVERIFIED_RULE"
    UNAPPROVED_RULE = "UNAPPROVED_RULE"
    CONFLICTED_RULE = "CONFLICTED_RULE"
    BLOCKED_RULE = "BLOCKED_RULE"
    MISSING_REQUIRED_DATA = "MISSING_REQUIRED_DATA"
    UNSUPPORTED_RULE = "UNSUPPORTED_RULE"
    UNSUPPORTED_CASE = "UNSUPPORTED_CASE"
    EXCEPTION_REQUIRED = "EXCEPTION_REQUIRED"
    AMBIGUOUS_REGULATION = "AMBIGUOUS_REGULATION"
